-- Seed data: Documented failure cases

INSERT INTO failure_cases (title, description, failure_type, failure_stage, root_causes, timeline_events, lessons_learned, industry, year_failed) VALUES

('Quibi', 
 'Quick bites streaming service that lasted 6 months before shutting down',
 'startup',
 'growth',
 ARRAY['Poor value proposition', 'Mobile-only strategy', 'No social sharing', 'Content not compelling enough'],
 '[{"month": 1, "event": "Launched with $1.75B funding"}, {"month": 2, "event": "User acquisition stalled"}, {"month": 4, "event": "Content creators frustrated with format"}, {"month": 6, "event": "Shut down"}]',
 'Mobile-only was too restrictive. Users want to watch on any device.',
 'Media/Streaming',
 2020),

('Theranos',
 'Blood testing startup that collapsed due to fraudulent claims',
 'startup',
 'scaling',
 ARRAY['Scientific fraud', 'Lack of transparency', 'Board incompetence', 'Cult of personality'],
 '[{"month": 1, "event": "Founded with revolutionary claims"}, {"month": 24, "event": "Walgreens partnership"}, {"month": 48, "event": "First whistleblower emerges"}, {"month": 72, "event": "WSJ investigation"}, {"month": 84, "event": "Company dissolved"}]',
 'Never overpromise and underdeliver. Board members should have domain expertise.',
 'Healthcare',
 2018),

('Juicero',
 '$400 WiFi-connected juicer that squeezed pre-packaged juice bags',
 'startup',
 'mvp',
 ARRAY['Solving non-problem', 'Extreme overengineering', 'High price point', 'Contempt for customers'],
 '[{"month": 1, "event": "Founded with $4.5M seed"}, {"month": 18, "event": "$118M Series B"}, {"month": 24, "event": "Launched product"}, {"month": 30, "event": "Viral video shows bags can be squeezed by hand"}, {"month": 36, "event": "Shut down"}]',
 'Build products people actually need, not what you think they need.',
 'Consumer Hardware',
 2017),

('Pets.com',
 'Online pet supplies retailer that IPOd and collapsed in 9 months',
 'startup',
 'mvp',
 ARRAY['Low margins', 'High customer acquisition cost', 'Logistics complexity', 'Bad unit economics'],
 '[{"month": 1, "event": "Launched during dot-com boom"}, {"month": 6, "event": "Famous sock puppet Super Bowl ad"}, {"month": 9, "event": "IPO at $11/share"}, {"month": 12, "event": "Stock at $0.19, company dissolved"}]',
 'Unit economics matter. Advertising cannot fix a broken business model.',
 'E-commerce',
 2000),

('Google Glass',
 'Wearable AR glasses that failed to gain consumer adoption',
 'product',
 'mature',
 ARRAY['Privacy concerns', 'Dorky design', 'Limited use cases', 'Price too high', 'Ecosystem immaturity'],
 '[{"month": 1, "event": "Project started as Google X"}, {"month": 36, "event": "Explorer edition released at $1500"}, {"month": 48, "event": "Privacy backlash intensifies"}, {"month": 60, "event": "Consumer version cancelled"}, {"month": 72, "event": "Pivoted to enterprise"}]',
 'Design matters. Social acceptability is a feature, not an afterthought.',
 'Wearables',
 2015),

('CyanogenMod/OS',
 'Custom Android ROM that tried to compete with Google',
 'startup',
 'growth',
 ARRAY['Overambition', ' alienated open source community', 'Competition from Google', 'Funding mismanagement'],
 '[{"month": 1, "event": "Community-driven ROM project"}, {"month": 30, "event": "Commercial company formed"}, {"month": 36, "event": "Microsoft investment"}, {"month": 42, "event": "CEO fired, key staff leave"}, {"month": 48, "event": "Project ended"}]',
 'Dont bite the hand that feeds. Open source communities are fragile.',
 'Software',
 2016),

('WeWork',
 'Office space sharing company with fraudulent business model',
 'company',
 'scaling',
 ARRAY['Fraudulent metrics', 'Cult of founder', 'Unicorn delusion', 'Lack of profitability path'],
 '[{"month": 1, "event": "Founded as GreenDesk"}, {"month": 60, "event": "$1B valuation"}, {"month": 96, "event": " IPO filing reveals governance issues"}, {"month": 100, "event": "IPO cancelled, CEO fired"}, {"month": 108, "event": "SPAC merger at $9B (down from $47B)"}]',
 'Corporate governance matters. Board independence is not optional.',
 'Real Estate Tech',
 2019),

('Friendster',
 'Social network that predated Facebook and died due to technical debt',
 'startup',
 'growth',
 ARRAY['Technical debt', 'Slow performance', 'Failed pivot attempts', 'Competition'],
 '[{"month": 1, "event": "Launched as social network"}, {"month": 12, "event": "50M users, 10B pageviews/month"}, {"month": 18, "event": "Funding issues, leadership turmoil"}, {"month": 24, "event": "Facebook overtakes in users"}, {"month": 48, "event": "Acquired for scraps"}]',
 'Technical debt is a business risk. Performance is a feature.',
 'Social Media',
 2003);
